version: 2

multi-ecosystem-groups:
  weekly-deps:
    schedule:
      interval: weekly
      day: monday

updates:
  - package-ecosystem: uv
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: weekly-deps

  - package-ecosystem: docker
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: weekly-deps

  - package-ecosystem: pre-commit
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: weekly-deps

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: weekly-deps
